// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dnlivtdghddphwkzsotg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRubGl2dGRnaGRkcGh3a3pzb3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzOTQ3ODcsImV4cCI6MjA2Nzk3MDc4N30.gkNZqskL9enimADIRLXNw7l7WYKBEPdSKPvWS_e3oOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});